export interface Room{
        id: string,
        hotelId: string,
        hotelName: string,
        name: string,
        type: string,
        description: string,
        image: string,
        gallery: string[],
        pricePerNight: number,
        size: number,
        beds: number,
        guests: number,
        amenities: string[],
    }