import {
    Utensils,
    Wifi,
    Dumbbell,
    ConciergeBell,
    Waves,
    Crown,
    Car,
    PartyPopper,
    Moon,
    Ship,
    Umbrella,
    Baby,
    CarFront,
    Sparkles,
    BellRing,
    Flag,
} from "lucide-react";

export const amenityIcons = {
    "مطعم راقي": Utensils,
    "إنترنت مجاني": Wifi,
    "نادي صحي": Dumbbell,
    "خدمة الكونسيرج": ConciergeBell,
    "إطلالة على الكورنيش": Waves,
    "إطلالة على البحر":Ship,
    "مسبح لانهائي": Waves,
    "صالة كبار الشخصيات": Crown,
    "خدمة الغرف ٢٤/٧": BellRing,
    "موقف سيارات خاص": Car,
    "قاعة احتفالات": PartyPopper,
    "مسجد": Moon,
    "مركز غوص": Ship,
    "شاطئ خاص": Umbrella,
    "سبا فاخر":Sparkles,
    "ملعب جولف": Flag,
    "نادي أطفال": Baby,
    "ليموزين خاص": CarFront,
} as const;